<a href="https://colab.research.google.com/github/bforoura/Transformers/blob/main/nlp_transformers_ch1_ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.special import softmax

In [2]:
print("Step 1: Input : 3 inputs, d_model=4")
x =np.array([[1.0, 0.0, 1.0, 0.0],   # Input 1
             [0.0, 2.0, 0.0, 2.0],   # Input 2
             [1.0, 1.0, 1.0, 1.0]])  # Input 3

print(x)

Step 1: Input : 3 inputs, d_model=4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


In [3]:
print("Step 2: weights 3 dimensions x d_model=4")

w_query =np.array([[1, 0, 1],
                   [1, 0, 0],
                   [0, 0, 1],
                   [0, 1, 1]])

w_key =np.array([[0, 0, 1],
                 [1, 1, 0],
                 [0, 1, 0],
                 [1, 1, 0]])

w_value = np.array([[0, 2, 0],
                    [0, 3, 0],
                    [1, 0, 3],
                    [1, 1, 0]])


Step 2: weights 3 dimensions x d_model=4


In [4]:
print("w_query")
print(w_query)

print("")

print("w_key")
print(w_key)

print("")

print("w_value")
print(w_value)


w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]

w_key
[[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 0]]

w_value
[[0 2 0]
 [0 3 0]
 [1 0 3]
 [1 1 0]]


In [5]:
print("Step 3: Matrix multiplication to obtain Q,K,V")
print("Query: x * w_query")

Q=np.matmul(x,w_query)
print(Q)


Step 3: Matrix multiplication to obtain Q,K,V
Query: x * w_query
[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]


In [6]:
print("Key: x * w_key")
K=np.matmul(x,w_key)
print(K)

print()

print("Value: x * w_value")
V=np.matmul(x,w_value)
print(V)


Key: x * w_key
[[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]]

Value: x * w_value
[[1. 2. 3.]
 [2. 8. 0.]
 [2. 6. 3.]]


In [7]:
print("Step 4: Scaled Attention Scores")
k_d = 1   #square root of k_d=3 rounded down to 1 for this example
attention_scores = (Q @ K.transpose())/k_d

print(attention_scores)

Step 4: Scaled Attention Scores
[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


In [8]:
print("Step 5: Scaled softmax attention_scores for each vector")

attention_scores[0]=softmax(attention_scores[0])
attention_scores[1]=softmax(attention_scores[1])
attention_scores[2]=softmax(attention_scores[2])

print(attention_scores[0])
print(attention_scores[1])
print(attention_scores[2])


Step 5: Scaled softmax attention_scores for each vector
[0.06337894 0.46831053 0.46831053]
[6.03366485e-06 9.82007865e-01 1.79861014e-02]
[2.95387223e-04 8.80536902e-01 1.19167711e-01]


In [9]:
print("Step 6: attention value obtained by score1/k_d * V")
print(V[0])
print(V[1])
print(V[2])

print("Attention 1")
attention1=attention_scores[0].reshape(-1,1)
attention1=attention_scores[0][0]*V[0]
print(attention1)

print("Attention 2")
attention2=attention_scores[0][1]*V[1]
print(attention2)

print("Attention 3")
attention3=attention_scores[0][2]*V[2]
print(attention3)

Step 6: attention value obtained by score1/k_d * V
[1. 2. 3.]
[2. 8. 0.]
[2. 6. 3.]
Attention 1
[0.06337894 0.12675788 0.19013681]
Attention 2
[0.93662106 3.74648425 0.        ]
Attention 3
[0.93662106 2.80986319 1.40493159]


In [10]:
print("Step7: summed the results to create the first line of the output matrix")
attention_input1 = attention1+attention2+attention3

print(attention_input1)


Step7: summed the results to create the first line of the output matrix
[1.93662106 6.68310531 1.59506841]


In [11]:
print("Step 8: Step 1 to 7 for inputs 1 to 3")
#We assume we have 3 results with learned weights (they were not trained in this example)
#We assume we are implementing the original Transformer paper. We will have 3 results of 64 dimensions each

attention_head1=np.random.random((3, 64))
print(attention_head1)



Step 8: Step 1 to 7 for inputs 1 to 3
[[0.13148203 0.03829168 0.2861673  0.31683066 0.86577224 0.80289711
  0.26612834 0.96102523 0.38889388 0.19143942 0.68095002 0.06567193
  0.31257388 0.40147144 0.24104979 0.4254851  0.4240913  0.82164621
  0.12624546 0.13767719 0.09382273 0.348346   0.74473046 0.14426032
  0.88146838 0.07769864 0.73300855 0.39572125 0.03165128 0.10091833
  0.10874704 0.2888105  0.27107165 0.76688586 0.24758366 0.20043679
  0.73354091 0.60211126 0.01949827 0.80549637 0.17158278 0.59693327
  0.90329506 0.13319332 0.53164499 0.29662379 0.92201489 0.19226347
  0.48081424 0.61344444 0.86574986 0.86009255 0.79683483 0.26662833
  0.40325268 0.11063081 0.58244665 0.11101545 0.44066732 0.20238456
  0.52893348 0.62074621 0.38880004 0.09131379]
 [0.27282496 0.04187776 0.88978867 0.37223828 0.49526882 0.18930514
  0.75242757 0.18093828 0.26784013 0.36987726 0.76751937 0.63509726
  0.21152427 0.37293889 0.87135326 0.43389632 0.36783138 0.14234065
  0.75890675 0.29176423 0.65761

In [12]:
print("Step 9: We assume we have trained the 8 heads of the attentionsub-layer")
z0h1=np.random.random((3, 64))
z1h2=np.random.random((3, 64))
z2h3=np.random.random((3, 64))
z3h4=np.random.random((3, 64))
z4h5=np.random.random((3, 64))
z5h6=np.random.random((3, 64))
z6h7=np.random.random((3, 64))
z7h8=np.random.random((3, 64))

print("shape of one head",z0h1.shape,"dimension of 8 heads",64*8)


Step 9: We assume we have trained the 8 heads of the attentionsub-layer
shape of one head (3, 64) dimension of 8 heads 512


In [13]:
print("Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 ouput dimension of the model")
output_attention=np.hstack((z0h1,z1h2,z2h3,z3h4,z4h5,z5h6,z6h7,z7h8))

print(output_attention)



Step 10: Concantenation of heads 1 to 8 to obtain the original 8x64=512 ouput dimension of the model
[[0.61742966 0.61558092 0.25181767 ... 0.23635132 0.37672259 0.61960927]
 [0.3847216  0.05432725 0.44269613 ... 0.32515866 0.45396557 0.43783078]
 [0.81253515 0.1135622  0.79508043 ... 0.0579154  0.65363546 0.08278254]]


In [14]:
# We first ensure that Hugging Face's transformers are installed:

!pip -qq install transformers


     |████████████████████████████████| 4.9 MB 5.1 MB/s 
     |████████████████████████████████| 6.6 MB 39.5 MB/s 
     |████████████████████████████████| 163 kB 69.2 MB/s 


In [15]:
# We then import the Hugging Face pipeline, which contains several transformer usages:

from transformers import pipeline



In [22]:
#  to illustrate the Transformer model of this chapter, we activate the 
# translator model and enter a sentence to translate from English to French:

translator = pipeline("translation_en_to_fr")

#One line of code!
print(translator("It is easy to translate languages with transformers", max_length=40))



No model was supplied, defaulted to t5-base and revision 686f1db (https://huggingface.co/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'translation_text': "Il est facile de traduire des langues à l'aide de transformateurs"}]
