<a href="https://colab.research.google.com/github/bforoura/Transformers/blob/main/nlp_transformers_ch1_ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.special import softmax

In [2]:
print("Step 1: Input : 3 inputs, d_model=4")
x =np.array([[1.0, 0.0, 1.0, 0.0],   # Input 1
             [0.0, 2.0, 0.0, 2.0],   # Input 2
             [1.0, 1.0, 1.0, 1.0]])  # Input 3

print(x)

Step 1: Input : 3 inputs, d_model=4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


In [7]:
print("Step 2: weights 3 dimensions x d_model=4")

w_query =np.array([[1, 0, 1],
                   [1, 0, 0],
                   [0, 0, 1],
                   [0, 1, 1]])

w_key =np.array([[0, 0, 1],
                 [1, 1, 0],
                 [0, 1, 0],
                 [1, 1, 0]])

w_value = np.array([[0, 2, 0],
                    [0, 3, 0],
                    [1, 0, 3],
                    [1, 1, 0]])


Step 2: weights 3 dimensions x d_model=4


In [9]:
print("w_query")
print(w_query)

print("")

print("w_key")
print(w_key)

print("")

print("w_value")
print(w_value)


w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]

w_key
[[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 0]]

w_value
[[0 2 0]
 [0 3 0]
 [1 0 3]
 [1 1 0]]


In [10]:
print("Step 3: Matrix multiplication to obtain Q,K,V")
print("Query: x * w_query")

Q=np.matmul(x,w_query)
print(Q)


Step 3: Matrix multiplication to obtain Q,K,V
Query: x * w_query
[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]
