<a href="https://colab.research.google.com/github/bforoura/Transformers/blob/main/nlp_transformers_ch1_ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.special import softmax

In [2]:
print("Step 1: Input : 3 inputs, d_model=4")
x =np.array([[1.0, 0.0, 1.0, 0.0],   # Input 1
             [0.0, 2.0, 0.0, 2.0],   # Input 2
             [1.0, 1.0, 1.0, 1.0]])  # Input 3

print(x)

Step 1: Input : 3 inputs, d_model=4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


In [7]:
print("Step 2: weights 3 dimensions x d_model=4")

w_query =np.array([[1, 0, 1],
                   [1, 0, 0],
                   [0, 0, 1],
                   [0, 1, 1]])

w_key =np.array([[0, 0, 1],
                 [1, 1, 0],
                 [0, 1, 0],
                 [1, 1, 0]])

w_value = np.array([[0, 2, 0],
                    [0, 3, 0],
                    [1, 0, 3],
                    [1, 1, 0]])


Step 2: weights 3 dimensions x d_model=4


In [9]:
print("w_query")
print(w_query)

print("")

print("w_key")
print(w_key)

print("")

print("w_value")
print(w_value)


w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]

w_key
[[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 0]]

w_value
[[0 2 0]
 [0 3 0]
 [1 0 3]
 [1 1 0]]


In [10]:
print("Step 3: Matrix multiplication to obtain Q,K,V")
print("Query: x * w_query")

Q=np.matmul(x,w_query)
print(Q)


Step 3: Matrix multiplication to obtain Q,K,V
Query: x * w_query
[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]


In [13]:
print("Key: x * w_key")
K=np.matmul(x,w_key)
print(K)

print()

print("Value: x * w_value")
V=np.matmul(x,w_value)
print(V)


Key: x * w_key
[[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]]

Value: x * w_value
[[1. 2. 3.]
 [2. 8. 0.]
 [2. 6. 3.]]


In [14]:
print("Step 4: Scaled Attention Scores")
k_d = 1   #square root of k_d=3 rounded down to 1 for this example
attention_scores = (Q @ K.transpose())/k_d

print(attention_scores)

Step 4: Scaled Attention Scores
[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


In [15]:
print("Step 5: Scaled softmax attention_scores for each vector")

attention_scores[0]=softmax(attention_scores[0])
attention_scores[1]=softmax(attention_scores[1])
attention_scores[2]=softmax(attention_scores[2])

print(attention_scores[0])
print(attention_scores[1])
print(attention_scores[2])


Step 5: Scaled softmax attention_scores for each vector
[0.06337894 0.46831053 0.46831053]
[6.03366485e-06 9.82007865e-01 1.79861014e-02]
[2.95387223e-04 8.80536902e-01 1.19167711e-01]


In [16]:
print("Step 6: attention value obtained by score1/k_d * V")
print(V[0])
print(V[1])
print(V[2])

print("Attention 1")
attention1=attention_scores[0].reshape(-1,1)
attention1=attention_scores[0][0]*V[0]
print(attention1)

print("Attention 2")
attention2=attention_scores[0][1]*V[1]
print(attention2)

print("Attention 3")
attention3=attention_scores[0][2]*V[2]
print(attention3)

Step 6: attention value obtained by score1/k_d * V
[1. 2. 3.]
[2. 8. 0.]
[2. 6. 3.]
Attention 1
[0.06337894 0.12675788 0.19013681]
Attention 2
[0.93662106 3.74648425 0.        ]
Attention 3
[0.93662106 2.80986319 1.40493159]


In [17]:
print("Step7: summed the results to create the first line of the output matrix")
attention_input1 = attention1+attention2+attention3

print(attention_input1)


Step7: summed the results to create the first line of the output matrix
[1.93662106 6.68310531 1.59506841]


In [18]:
print("Step 8: Step 1 to 7 for inputs 1 to 3")
#We assume we have 3 results with learned weights (they were not trained in this example)
#We assume we are implementing the original Transformer paper. We will have 3 results of 64 dimensions each

attention_head1=np.random.random((3, 64))
print(attention_head1)



Step 8: Step 1 to 7 for inputs 1 to 3
[[0.11417149 0.56508858 0.83043368 0.46479419 0.89585463 0.81565501
  0.61825008 0.55572652 0.43044949 0.29045964 0.50713898 0.36517847
  0.06840972 0.21334416 0.45282906 0.33546611 0.13134107 0.38698329
  0.33146688 0.30270807 0.97545433 0.53931672 0.1217342  0.7332061
  0.14435247 0.71404858 0.90980394 0.49646041 0.87902671 0.48991826
  0.61842771 0.44879244 0.38941825 0.37126104 0.11585137 0.36754874
  0.17181227 0.01507133 0.58472956 0.2737691  0.97442183 0.78197063
  0.45777076 0.91905505 0.43796158 0.51809903 0.15855206 0.50583513
  0.53460292 0.50367346 0.97413282 0.03048474 0.77127186 0.64982201
  0.34959424 0.09105251 0.65578789 0.10366049 0.35116811 0.52891349
  0.85874566 0.47422149 0.49699314 0.17381452]
 [0.67435935 0.97851823 0.64526101 0.36766504 0.08818583 0.31479515
  0.22407253 0.6428197  0.55444163 0.79638096 0.94569059 0.25201594
  0.71096408 0.30105015 0.10269438 0.08137369 0.48360289 0.02466192
  0.9246544  0.35386207 0.815601